ALTER TABLE pessoa_juridica
ADD COLUMN nome_fantasia VARCHAR(255) NOT NULL,
ADD COLUMN razao_social VARCHAR(255) NOT NULL,
ADD COLUMN telefone_comercial VARCHAR(20) NOT NULL,
ADD COLUMN telefone_celular VARCHAR(20),
ADD COLUMN email_faturamento VARCHAR(255) NOT NULL,
ADD COLUMN cep VARCHAR(10) NOT NULL,
ADD COLUMN endereco TEXT,
ADD COLUMN responsavel_nome VARCHAR(255),
ADD COLUMN responsavel_cpf VARCHAR(14) NOT NULL,
ADD COLUMN responsavel_rg VARCHAR(20) NOT NULL,
ADD COLUMN responsavel_data_emissao DATE,
ADD COLUMN responsavel_orgao VARCHAR(20),
ADD COLUMN responsavel_nascimento DATE NOT NULL,
ADD COLUMN responsavel_cargo VARCHAR(100),
ADD COLUMN responsavel_cep VARCHAR(10) NOT NULL,
ADD COLUMN responsavel_endereco TEXT,
ADD COLUMN detalhes_contrato TEXT,
ADD COLUMN quantidade_pontos INTEGER,
ADD COLUMN pergunta TEXT;